/**
 * 技能数据库
 * 基于 http://spongem.com/yysls/data/skill_data.js
 */

// 技能修正器
export interface SkillModifiers {
  连星?: number;
  断石?: boolean;
  三穷?: number;
  [key: string]: number | boolean | undefined;
}

// 技能数据结构
export interface SkillInfo {
  modifiers: SkillModifiers;
  outerRatio: number;
  fixed: number;
  eleRatio: number;
  exMinATK: number;
  exMaxATK: number;
  exATK: number;
  exCrit: number;
  exCritDmg: number;
  exIntent: number;
  exIntentDmg: number;
  exDmg: number;
  exPen: number;
  isCharge: number;
  type: string;
  weaponType: string;
  element: string;
  special: string;
  force: string;
}

// 技能数据库类型
export type SkillDatabase = Record<string, SkillInfo>;

// 各流派技能数据
export const SkillData: Record<string, SkillDatabase> = {
  破竹尘: {
    "尘绳标Q(失魂)": {
      modifiers: { 连星: 0.15, 断石: false },
      outerRatio: 3.1428,
      fixed: 869,
      eleRatio: 4.7143,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "绳标",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "尘流韵(失魂)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 2.8285,
      fixed: 782,
      eleRatio: 4.2429,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "尘流韵HIT(失魂)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 1.1314,
      fixed: 313,
      eleRatio: 1.6971,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "摩诃*7(失魂)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 4.9,
      fixed: 1356,
      eleRatio: 7.35,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "摩诃*8(失魂)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 5.6,
      fixed: 1550,
      eleRatio: 8.4,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "尘余韵(失魂)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 0.9425,
      fixed: 261,
      eleRatio: 1.4143,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "尘归鸿(失魂)": {
      modifiers: { 连星: 0.15, 断石: false },
      outerRatio: 2.5143,
      fixed: 696,
      eleRatio: 3.7714,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "尘归鸿HIT(失魂)": {
      modifiers: { 连星: 0.15, 断石: false },
      outerRatio: 0.5657,
      fixed: 156,
      eleRatio: 0.8486,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "破竹",
      special: "无",
      force: "无",
    },
    绳标精通: {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 0.38,
      fixed: 105,
      eleRatio: 0.57,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "绳标",
      element: "破竹",
      special: "定音",
      force: "无",
    },
    蓄劲: {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 0.8,
      fixed: 221,
      eleRatio: 1.2,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "破竹",
      special: "无",
      force: "无",
    },
  },
  破竹鸢: {
    "鸢扇Q(失魂)": {
      modifiers: { 连星: 0.15, 断石: false },
      outerRatio: 2.9714,
      fixed: 822,
      eleRatio: 4.4571,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "扇",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "鸢流韵(失魂)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 2.8285,
      fixed: 782,
      eleRatio: 4.2429,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "鸢流韵HIT(失魂)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 1.1314,
      fixed: 313,
      eleRatio: 1.6971,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "摩诃*7(失魂)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 4.9,
      fixed: 1356,
      eleRatio: 7.35,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "摩诃*8(失魂)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 5.6,
      fixed: 1550,
      eleRatio: 8.4,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "鸢余韵(失魂)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 0.9425,
      fixed: 261,
      eleRatio: 1.4143,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "鸢归鸿(失魂)": {
      modifiers: { 连星: 0.15, 断石: false },
      outerRatio: 2.5143,
      fixed: 696,
      eleRatio: 3.7714,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "鸢归鸿HIT(失魂)": {
      modifiers: { 连星: 0.15, 断石: false },
      outerRatio: 0.5657,
      fixed: 156,
      eleRatio: 0.8486,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "破竹",
      special: "无",
      force: "无",
    },
    扇精通: {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 0.38,
      fixed: 105,
      eleRatio: 0.57,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "扇",
      element: "破竹",
      special: "定音",
      force: "无",
    },
    蓄劲: {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 0.8,
      fixed: 221,
      eleRatio: 1.2,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "破竹",
      special: "无",
      force: "无",
    },
  },
  鸣金虹: {
    "虹剑Q(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 2.4,
      fixed: 664,
      eleRatio: 3.6,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "剑",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "奏绝(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 2.16,
      fixed: 598,
      eleRatio: 3.24,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "奏绝HIT(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 0.72,
      fixed: 199,
      eleRatio: 1.08,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "虹纵(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 3.6,
      fixed: 996,
      eleRatio: 5.4,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "虹御(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 1.44,
      fixed: 398,
      eleRatio: 2.16,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "虹钟(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 2.88,
      fixed: 797,
      eleRatio: 4.32,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "虹钟HIT(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 0.576,
      fixed: 159,
      eleRatio: 0.864,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "金音*4(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 2.88,
      fixed: 797,
      eleRatio: 4.32,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "金音*5(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 3.6,
      fixed: 996,
      eleRatio: 5.4,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "金音*6(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 4.32,
      fixed: 1195,
      eleRatio: 6.48,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    剑精通: {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 0.36,
      fixed: 100,
      eleRatio: 0.54,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "剑",
      element: "鸣金",
      special: "定音",
      force: "无",
    },
  },
  鸣金影: {
    "影剑Q(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 2.52,
      fixed: 697,
      eleRatio: 3.78,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "剑",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "奏绝(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 2.16,
      fixed: 598,
      eleRatio: 3.24,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "奏绝HIT(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 0.72,
      fixed: 199,
      eleRatio: 1.08,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "影纵(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 3.78,
      fixed: 1046,
      eleRatio: 5.67,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "影御(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 1.512,
      fixed: 418,
      eleRatio: 2.268,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "影钟(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 3.024,
      fixed: 837,
      eleRatio: 4.536,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "影钟HIT(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 0.6048,
      fixed: 167,
      eleRatio: 0.9072,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "金音*4(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 2.88,
      fixed: 797,
      eleRatio: 4.32,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "金音*5(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 3.6,
      fixed: 996,
      eleRatio: 5.4,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    "金音*6(气盛)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 4.32,
      fixed: 1195,
      eleRatio: 6.48,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0.15,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "鸣金",
      special: "无",
      force: "无",
    },
    剑精通: {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 0.36,
      fixed: 100,
      eleRatio: 0.54,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "剑",
      element: "鸣金",
      special: "定音",
      force: "无",
    },
  },
  破竹风: {
    "风绳标Q(失魂)": {
      modifiers: { 连星: 0.15, 断石: false },
      outerRatio: 3.1428,
      fixed: 869,
      eleRatio: 4.7143,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "绳标",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "风一苇(失魂)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 2.5143,
      fixed: 696,
      eleRatio: 3.7714,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "风一苇HIT(失魂)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 0.6286,
      fixed: 174,
      eleRatio: 0.9429,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "风余韵(失魂)": {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 0.9425,
      fixed: 261,
      eleRatio: 1.4143,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "风归鸿(失魂)": {
      modifiers: { 连星: 0.15, 断石: false },
      outerRatio: 2.5143,
      fixed: 696,
      eleRatio: 3.7714,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "破竹",
      special: "无",
      force: "无",
    },
    "风归鸿HIT(失魂)": {
      modifiers: { 连星: 0.15, 断石: false },
      outerRatio: 0.5657,
      fixed: 156,
      eleRatio: 0.8486,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.27,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0.05,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "破竹",
      special: "无",
      force: "无",
    },
    绳标精通: {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 0.38,
      fixed: 105,
      eleRatio: 0.57,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "绳标",
      element: "破竹",
      special: "定音",
      force: "无",
    },
    蓄劲: {
      modifiers: { 连星: 0, 断石: false },
      outerRatio: 0.8,
      fixed: 221,
      eleRatio: 1.2,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "破竹",
      special: "无",
      force: "无",
    },
  },
  裂石威: {
    威拳甲Q: {
      modifiers: { 断石: false },
      outerRatio: 2.8,
      fixed: 775,
      eleRatio: 4.2,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "拳甲",
      element: "裂石",
      special: "无",
      force: "无",
    },
    威迸裂: {
      modifiers: { 断石: false },
      outerRatio: 2.24,
      fixed: 620,
      eleRatio: 3.36,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "裂石",
      special: "无",
      force: "无",
    },
    威迸裂HIT: {
      modifiers: { 断石: false },
      outerRatio: 0.56,
      fixed: 155,
      eleRatio: 0.84,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "裂石",
      special: "无",
      force: "无",
    },
    "威碎岩*5": {
      modifiers: { 断石: false },
      outerRatio: 3.5,
      fixed: 969,
      eleRatio: 5.25,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "裂石",
      special: "无",
      force: "无",
    },
    "威碎岩*6": {
      modifiers: { 断石: false },
      outerRatio: 4.2,
      fixed: 1163,
      eleRatio: 6.3,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "裂石",
      special: "无",
      force: "无",
    },
    "威碎岩*7": {
      modifiers: { 断石: false },
      outerRatio: 4.9,
      fixed: 1356,
      eleRatio: 7.35,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "裂石",
      special: "无",
      force: "无",
    },
    威刹那: {
      modifiers: { 断石: false },
      outerRatio: 1.68,
      fixed: 465,
      eleRatio: 2.52,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "裂石",
      special: "无",
      force: "无",
    },
    威刹那HIT: {
      modifiers: { 断石: false },
      outerRatio: 0.336,
      fixed: 93,
      eleRatio: 0.504,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "裂石",
      special: "无",
      force: "无",
    },
    拳甲精通: {
      modifiers: { 断石: false },
      outerRatio: 0.35,
      fixed: 97,
      eleRatio: 0.525,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "拳甲",
      element: "裂石",
      special: "定音",
      force: "无",
    },
  },
  "裂石钧（双切）": {
    钧双刀Q: {
      modifiers: { 断石: false },
      outerRatio: 2.6,
      fixed: 720,
      eleRatio: 3.9,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "双刀",
      element: "裂石",
      special: "无",
      force: "无",
    },
    钧陌刀Q: {
      modifiers: { 断石: false },
      outerRatio: 2.8,
      fixed: 775,
      eleRatio: 4.2,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "陌刀",
      element: "裂石",
      special: "无",
      force: "无",
    },
    钧回风: {
      modifiers: { 断石: false },
      outerRatio: 2.1,
      fixed: 581,
      eleRatio: 3.15,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "裂石",
      special: "无",
      force: "无",
    },
    钧回风HIT: {
      modifiers: { 断石: false },
      outerRatio: 0.42,
      fixed: 116,
      eleRatio: 0.63,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "裂石",
      special: "无",
      force: "无",
    },
    钧碎岩: {
      modifiers: { 断石: false },
      outerRatio: 3.5,
      fixed: 969,
      eleRatio: 5.25,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "裂石",
      special: "无",
      force: "无",
    },
    双刀精通: {
      modifiers: { 断石: false },
      outerRatio: 0.33,
      fixed: 91,
      eleRatio: 0.495,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "双刀",
      element: "裂石",
      special: "定音",
      force: "无",
    },
    陌刀精通: {
      modifiers: { 断石: false },
      outerRatio: 0.35,
      fixed: 97,
      eleRatio: 0.525,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "陌刀",
      element: "裂石",
      special: "定音",
      force: "无",
    },
  },
  "裂石钧（纯唐）": {
    钧陌刀Q: {
      modifiers: { 断石: false },
      outerRatio: 2.8,
      fixed: 775,
      eleRatio: 4.2,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "陌刀",
      element: "裂石",
      special: "无",
      force: "无",
    },
    钧回风: {
      modifiers: { 断石: false },
      outerRatio: 2.1,
      fixed: 581,
      eleRatio: 3.15,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "裂石",
      special: "无",
      force: "无",
    },
    钧回风HIT: {
      modifiers: { 断石: false },
      outerRatio: 0.42,
      fixed: 116,
      eleRatio: 0.63,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "裂石",
      special: "无",
      force: "无",
    },
    钧碎岩: {
      modifiers: { 断石: false },
      outerRatio: 3.5,
      fixed: 969,
      eleRatio: 5.25,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "心法",
      weaponType: "N/A",
      element: "裂石",
      special: "无",
      force: "无",
    },
    陌刀精通: {
      modifiers: { 断石: false },
      outerRatio: 0.35,
      fixed: 97,
      eleRatio: 0.525,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "陌刀",
      element: "裂石",
      special: "定音",
      force: "无",
    },
  },
  牵丝霖: {
    "霖枪Q(飞雀)": {
      modifiers: { 断石: false },
      outerRatio: 2.64,
      fixed: 731,
      eleRatio: 3.96,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.2,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "枪",
      element: "牵丝",
      special: "无",
      force: "无",
    },
    霖天雨: {
      modifiers: { 断石: false },
      outerRatio: 1.98,
      fixed: 548,
      eleRatio: 2.97,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.2,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "牵丝",
      special: "无",
      force: "无",
    },
    霖天雨HIT: {
      modifiers: { 断石: false },
      outerRatio: 0.396,
      fixed: 110,
      eleRatio: 0.594,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.2,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "牵丝",
      special: "无",
      force: "无",
    },
    霖乱花: {
      modifiers: { 断石: false },
      outerRatio: 2.31,
      fixed: 639,
      eleRatio: 3.465,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.2,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "牵丝",
      special: "无",
      force: "无",
    },
    霖乱花HIT: {
      modifiers: { 断石: false },
      outerRatio: 0.462,
      fixed: 128,
      eleRatio: 0.693,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.2,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "牵丝",
      special: "无",
      force: "无",
    },
    霖疾羽: {
      modifiers: { 断石: false },
      outerRatio: 1.65,
      fixed: 457,
      eleRatio: 2.475,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.2,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "牵丝",
      special: "无",
      force: "无",
    },
    霖疾羽HIT: {
      modifiers: { 断石: false },
      outerRatio: 0.33,
      fixed: 91,
      eleRatio: 0.495,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.2,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "牵丝",
      special: "无",
      force: "无",
    },
    枪精通: {
      modifiers: { 断石: false },
      outerRatio: 0.33,
      fixed: 91,
      eleRatio: 0.495,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "枪",
      element: "牵丝",
      special: "定音",
      force: "无",
    },
  },
  牵丝玉: {
    "玉伞Q(飞雀)": {
      modifiers: { 断石: false },
      outerRatio: 2.508,
      fixed: 694,
      eleRatio: 3.762,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.2,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "伞",
      element: "牵丝",
      special: "无",
      force: "无",
    },
    玉天雨: {
      modifiers: { 断石: false },
      outerRatio: 1.881,
      fixed: 521,
      eleRatio: 2.8215,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.2,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "牵丝",
      special: "无",
      force: "无",
    },
    玉天雨HIT: {
      modifiers: { 断石: false },
      outerRatio: 0.3762,
      fixed: 104,
      eleRatio: 0.5643,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.2,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "牵丝",
      special: "无",
      force: "无",
    },
    玉乱花: {
      modifiers: { 断石: false },
      outerRatio: 2.1945,
      fixed: 607,
      eleRatio: 3.2918,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.2,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "牵丝",
      special: "无",
      force: "无",
    },
    玉乱花HIT: {
      modifiers: { 断石: false },
      outerRatio: 0.4389,
      fixed: 121,
      eleRatio: 0.6584,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.2,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "牵丝",
      special: "无",
      force: "无",
    },
    玉疾羽: {
      modifiers: { 断石: false },
      outerRatio: 1.5675,
      fixed: 434,
      eleRatio: 2.3513,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.2,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "牵丝",
      special: "无",
      force: "无",
    },
    玉疾羽HIT: {
      modifiers: { 断石: false },
      outerRatio: 0.3135,
      fixed: 87,
      eleRatio: 0.4703,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0.2,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "奇术",
      weaponType: "单体奇术",
      element: "牵丝",
      special: "无",
      force: "无",
    },
    伞精通: {
      modifiers: { 断石: false },
      outerRatio: 0.3135,
      fixed: 87,
      eleRatio: 0.4703,
      exMinATK: 0,
      exMaxATK: 0,
      exATK: 0,
      exCrit: 0,
      exCritDmg: 0,
      exIntent: 0,
      exIntentDmg: 0,
      exDmg: 0,
      exPen: 0,
      isCharge: 0,
      type: "武器",
      weaponType: "伞",
      element: "牵丝",
      special: "定音",
      force: "无",
    },
  },
};
